#save_folder: Experiments/Baseline_unetr/DiceFocal  #Experiments/test
save_folder: Experiments/Baseline_vnet/Dice  #Experiments/test

Training_Dataset:
  #patient_data_list_path: "dataset/lists/sample_100.txt"
  patient_data_list_path: "Brain_Tumor_segmentaion3D/dataset/lists/train_val_test_splits/train_split.txt"
  no_classes: 4
  src_folder: "C:/Users/sumuk/OneDrive/Desktop/NCSU_related/Courses_and_stuff/Courses_and_stuff/NCSU_courses_and_books/ECE_542/FinalProj/"

Validation_Dataset:
  #patient_data_list_path: "dataset/lists/sample_100.txt"
  patient_data_list_path: "Brain_Tumor_segmentaion3D/dataset/lists/train_val_test_splits/val_split.txt"
  no_classes: 4
  src_folder: "C:/Users/sumuk/OneDrive/Desktop/NCSU_related/Courses_and_stuff/Courses_and_stuff/NCSU_courses_and_books/ECE_542/FinalProj/"

Test_Dataset:
  #patient_data_list_path: "dataset/lists/sample_100.txt"
  patient_data_list_path: "Brain_Tumor_segmentaion3D/dataset/lists/train_val_test_splits/test_split.txt"
  no_classes: 4
  src_folder: "C:/Users/sumuk/OneDrive/Desktop/NCSU_related/Courses_and_stuff/Courses_and_stuff/NCSU_courses_and_books/ECE_542/FinalProj/"

Model:
  path: source_code.models.vnet.VNet
  params:
    spatial_dims: 3
    in_channels: 3
    out_channels: 4
    act: "elu"
    dropout_prob: 0.5
    dropout_dim: 3
    bias: False

Trainer:
  number_of_epochs: 100
#  loss:
#    path: monai.losses.DiceFocalLoss
#    params:
#      include_background: True
#      to_onehot_y: True
#      sigmoid: False
#      softmax: True
#      #other_act: None
#      squared_pred: False
#      jaccard: False
#      reduction: 'mean'
#      smooth_nr: 1e-05
#      smooth_dr: 1e-05
#      batch: False
#      gamma: 2.0
#      #focal_weight=None
#      lambda_dice: 1.0
#      lambda_focal: 1.0

  loss:
    path: monai.losses.DiceLoss
    params:
      include_background: True
      to_onehot_y: True
      sigmoid: False
      softmax: True
      #other_act: None
      squared_pred: False
      jaccard: False
      reduction: 'mean'
      smooth_nr: 1e-05
      smooth_dr: 1e-05
      batch: False
      #ce_weight: None
      #lambda_dice: 1.0
      #lambda_ce: 1.0

  optimizer:
    path: torch.optim.AdamW
    params:
        lr: 0.001


